<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.Playwright.NUnit" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit.Analyzers" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.Playwright.NUnit"/>
        <Using Include="NUnit.Framework"/>
        <Using Include="System.Text.RegularExpressions"/>
        <Using Include="System.Threading.Tasks"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RoslynRunner\RoslynRunner.csproj" />
      <ProjectReference Include="..\RoslynRunner.ApiTests\RoslynRunner.ApiTests.csproj" />
    </ItemGroup>

</Project>
