name: Build, Test, and Publish NuGet Tool
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build the project
        run: dotnet build RoslynRunner.sln
      - name: Build the legacy sample
        run: dotnet build
        working-directory: samples/LegacyWebApp

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Run API tests
        run: dotnet test RoslynRunner.ApiTests/RoslynRunner.ApiTests.csproj --logger "console;verbosity=detailed"

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
      - name: Pack the tool
        run: dotnet pack RoslynRunner/RoslynRunner.csproj -c Release -p:Version=${{ steps.extract_version.outputs.version }}
      - name: Publish to NuGet
        run: dotnet nuget push RoslynRunner/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
