name: Playwright Tests
on:
    workflow_dispatch:
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            RUN_PLAYWRIGHT_TESTS: "true"
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x
            - name: Build & Install
              run: dotnet build
            - name: Ensure browsers are installed
              run: pwsh RoslynRunner.EndToEndTests/bin/Debug/net9.0/playwright.ps1 install --with-deps
            - name: Build the legacy sample
              run: dotnet build
              working-directory: samples/LegacyWebApp
            - name: Run Playwright tests
              run: dotnet test --filter "Category=Playwright"
