name: Playwright Tests
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.0.x
            - name: Build & Install
              run: dotnet build
            - name: Ensure browsers are installed
              run: pwsh RoslynRunner.EndToEndTests/bin/Debug/net9.0/playwright.ps1 install --with-deps
            - name: Build the legacy sample
              run: dotnet build
              working-directory: samples/LegacyWebApp
            - name: Run your tests
              run: dotnet test
